### readAll repos
GET http://localhost:3000/api/repos 


### readby status privet/public repos
GET http://localhost:3000/api/repos?status=1


### create  repo
POST http://localhost:3000/api/repos/
Content-Type: application/json

{
  "id": "ezrtryhtg",
  "name": "repo1",
  "url": "localhost:3000",
  "isPrivate": "2"
}


### delete  repo
DELETE http://localhost:3000/api/repos/id:ezrtryhtg
Content-Type: application/json


###
GET http://localhost:3000/api/langs


###
GET http://localhost:3000/api/langs?language=HTML


###
POST http://localhost:3000/api/langs
Content-Type: application/json

{
  "id": "3",
  "label": "repo1",

}