version: "3.9"

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        restart: always
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5

    adminer:
        image: adminer
        ports:
            - 8080:8080
        container_name: adminer
        depends_on:
            db:
                condition: service_healthy

    api:
        build: ./server
        ports:
            - 4000:4000
        command: sh -c "npm run seed && npm run dev"
        environment:
            PORT: 4000
        restart: always
        volumes:
            - ./server:/app/
        depends_on:
            db:
                condition: service_healthy

    client:
        build: ./client
        ports:
            - 5173:5173
        command: npm run dev
        environment:
            PORT: 5173
        restart: always
        volumes:
            - ./client:/app/
            - /app/node_modules
